"""
    IDEIAS:

    ELEMENTO PRA RECUPERAR 1 VIDA
    BOTÃO DE PAUSE
    TEXTO DO TUTORIAL
    NIVEL 2
    MUSICA PRO NIVEL DOIS?
    NIVEL BOSS
    MUSICA PRO NIVEL BOSS
    PERSONALIZAR O MENU
    SOM DO GAME OVER
    SEPARAR AS FASES POR MODULOS

"""